# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-25 15:46
from __future__ import unicode_literals

from django.db import migrations
from rest_framework.validators import UniqueValidator
from FashaApi.models import UserSerializer
from rest_framework import serializers
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    # migrations.AlterField('UserSerializer','email',serializers.EmailField(required=True,
            # validators=[UniqueValidator(queryset=User.objects.all())]))
    ]
