# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashaApi', '0002_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='owner',
        ),
        migrations.AddField(
            model_name='poster',
            name='owner_id',
            field=models.EmailField(default='default', max_length=254),
        ),
    ]
