# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashaApi', '0003_auto_20170713_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
