# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashaApi', '0004_posterimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosterImage',
        ),
        migrations.AddField(
            model_name='poster',
            name='image',
            field=models.ImageField(default='/media/default/default_poster_image.jpg', upload_to='images/%Y/%m/%d'),
        ),
    ]
