# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('FashaApi', '0005_auto_20170721_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='fashion', max_length=220, size=20),
        ),
    ]
